version: '3.8'

services:
  checkup-bot-backend:
    image: checkup-bot/backend
    build:
      context: checkup-bot-backend
      dockerfile: Dockerfile
    networks:
      - checkup-bot-network

  checkup-bot-frontend:
    image: checkup-bot/frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    networks:
      - checkup-bot-network
  
  nginx:
    image: nginx:latest
    container_name: nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - checkup-bot-network

networks:
  checkup-bot-network:
