name: Checkup bot build and deploy to AWS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven
      - 
        name: Build
        run: mvn -B package --file ./checkup-bot-backend/pom.xml
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./checkup-bot-backend
          file: ./Dockerfile
          push: true
          tags: checkupbot/checkup-bot:latest