name: Checkup bot build and deploy to AWS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs: 
  login:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - 
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/app:latest