name: Deploy frontend

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGION: 'us-central1'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: checkout
      uses: actions/checkout@v2

    - name: install gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT }}
        service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
        export_default_credentials: true
