name: Deploy Backend

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: checkout
      uses: actions/checkout@v2

    - name: install gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT }}
        service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
        export_default_credentials: true
    
    - name: build and push docker
      env:
        GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
      run: |
        gcloud auth configure-docker northamerica-northeast1-docker.pkg.dev
        docker build -t northamerica-northeast1-docker.pkg.dev/checkup-bot-stage/checkup-bot-stage/backend:latest ./checkup-bot-backend/
        docker push northamerica-northeast1-docker.pkg.dev/checkup-bot-stage/checkup-bot-stage/nginx:latest